name: whatsapp-scheduler
region: nyc
services:
  - name: backend
    github:
      repo: beborico1/whatsapp-scheduler
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: WHATSAPP_ACCESS_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_APP_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_PHONE_NUMBER_ID
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_VERIFY_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
    
  - name: worker
    github:
      repo: beborico1/whatsapp-scheduler
      branch: main
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    run_command: celery -A app.celery_app worker --loglevel=info
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: WHATSAPP_ACCESS_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_APP_ID
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_APP_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_PHONE_NUMBER_ID
        scope: RUN_TIME
        type: SECRET
      - key: WHATSAPP_VERIFY_TOKEN
        scope: RUN_TIME
        type: SECRET
    
  - name: frontend
    github:
      repo: beborico1/whatsapp-scheduler
      branch: main
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    
databases:
  - name: db
    engine: PG
    production: false
    
  - name: redis
    engine: REDIS
    production: false