# Docker Compose Override for Development
# This file is automatically loaded by docker-compose in development
# It overrides settings from docker-compose.yml for a better dev experience

services:
  backend:
    build:
      args:
        - DEV=true
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  celery_worker:
    environment:
      - LOG_LEVEL=DEBUG
    command: celery -A app.celery_app worker --loglevel=debug --concurrency=1

  celery_beat:
    environment:
      - LOG_LEVEL=DEBUG
    command: celery -A app.celery_app beat --loglevel=debug

  frontend:
    environment:
      - NODE_ENV=development
      - GENERATE_SOURCEMAP=true
      - ESLINT_NO_DEV_ERRORS=true
      - TSC_COMPILE_ON_ERROR=true
    stdin_open: true
    tty: true

  # Development-only services
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    profiles: ["dev-tools"]

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    profiles: ["dev-tools"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles: ["dev-tools"]