[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs", "postgresql"]

[phases.install]
cmds = [
    "cd backend && python -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"