[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && celery -A app.celery_app beat --loglevel=info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10