[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["python", "node"]
cmds = ["cd backend && pip install -r requirements.txt"]

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10