databases:
  - name: whatsapp-scheduler-db
    databaseName: whatsapp_scheduler
    user: whatsapp_user
    plan: free

services:
  - type: web
    name: whatsapp-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-scheduler-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false

  - type: worker
    name: whatsapp-worker
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && celery -A app.celery_app worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-scheduler-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false

  - type: cron
    name: whatsapp-beat
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && celery -A app.celery_app beat --loglevel=info"
    schedule: "*/1 * * * *"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-scheduler-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false

  - type: web
    name: whatsapp-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY